amazonProperties:
  endpointUrl: https://sqs.us-east-2.amazonaws.com/955353222907/globant-training-disney-queue
  region: us-east-2
  bucketName: globant-training-disney-created-from-cli
  queueName: globant-training-disney-queue

server.port: 8090
