amazonProperties:
  endpointUrl: https://s3.us-east-2.amazonaws.com
  accessKey: 
  secretKey: 
  bucketName: globant-training-disney-created-from-cli
  queueName: globant-training-disney-queue

server.port: 8090
