amazonProperties:
  endpointUrl: https://sqs.us-east-2.amazonaws.com/955353222907/globant-training-disney-queue
  accesskey: YOUR_ACCESS:KEY
  secretKey: YOUR_ACCESS:SECRET
  bucketName: globant-training-disney-created-from-cli
  queueName: globant-training-disney-queue

server.port: 8090
cloud.aws.region.static: us-east-2


